[workspace]
members = [
    "crates/alknet-vault",
    "crates/alknet-core",
    "crates/alknet-call",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://git.alk.dev/alkdev/alknet"

[workspace.dependencies]
irpc = "0.16"
irpc-derive = "0.16"